[package]
name = "deepmsg-client"
description = "deepmsg client: publications, subscriptions and the client conductor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
deepmsg-core = { path = "../core" }
deepmsg-cnc = { path = "../cnc" }

[lints]
workspace = true
