[package]
name = "deepmsg-codec"
description = "The SBE codecs, one generated crate per schema"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
deepmsg-codec-archive = { path = "archive" }
deepmsg-codec-archive-mark = { path = "archive-mark" }
deepmsg-codec-cluster = { path = "cluster" }
deepmsg-codec-cluster-mark = { path = "cluster-mark" }
deepmsg-codec-cluster-node-state = { path = "cluster-node-state" }

[lints]
workspace = true
